sudo: required

language: go #can be any language, just php for example

services:
  - docker

install:
    - echo "install nothing!" # put your normal pre-testing installs here
    

script:
    - docker build -t svrsunil/app .
    - echo "tests pass !" # put your normal testing scripts here

after_success:
  - docker build -t svrsunil/mysql ./mysql_config
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push svrsunil/app
  - docker push svrsunil/mysql

deploy:
    provider: elasticbeanstalk
    access_key_id: $ACCESS_KEY_ID
    secret_access_key:
      secure: "$secret_access_key"
    region: "ap-southeast-1"
    app: "DeployCI"
    env: "Deployci-env"
    bucket_name: "elasticbeanstalk-ap-southeast-1-167236807881"
    bucket_path: "DeployWeb"
    on:
        branch: master

notifications:
  email:
    recipients:
      - svrsunil@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
